### ISSUE TITLE
VirtualApp无法打开多个应用

### ISSUE THREAD

**Issue by prife** [prife/VirtualAppDoc#8]
VA的 版本还可以同时打开多个应用. [f8f8e93](https://github.com/asLody/VirtualApp/commit/f8f8e93842eb5c1fba47e07511b6a750f6595bd6)
master上最新代码 [cfc3228](https://github.com/asLody/VirtualApp/commit/cfc322820c8f1ea7e4d579e63cdcd4b29fa0ad69) 　已经不能打开同时打开多个应用，即使注释掉：

``` java
//HomePresenterImpl.java

    public void launchApp(AppModel model) {
        try {
            // VActivityManager.getInstance().killAllApps();   注释掉这一行也不能同时打开多个
            LoadingActivity.launch(mActivity, model);
        } catch (Throwable e) {
            e.printStackTrace();
        }
    }
```

**Comment by prife** [comment]
回归测试显示是这条提交 https://github.com/asLody/VirtualApp/commit/4d910040ac3d6659e09ecc2634543415334be1e1  提交导致的

**Comment by prife** [comment]
VA中打开今日头条有个必现的bug

复现步骤：
1. 安装今日头条和安装其他应用A
2. 打开应用A，然后从最近应用列表中回到VA，再此打开今日头条
结果：继续打开应用A，而非今日头条。

```
08-26 02:20:07.380 30771-30771/io.virtualapp:p7 E/VA-IO: offset=32
08-26 02:20:07.380 30771-30771/io.virtualapp:p7 D/VA-IO: replace art method.
08-26 02:20:07.380 30771-30771/io.virtualapp:p7 D/VA-IO: DONE java hook!
08-26 02:20:07.380 30771-30771/io.virtualapp:p7 I/VA-IO: End Native hooks SUCCESS!
08-26 02:20:07.421 30771-30771/io.virtualapp:p7 D/IOHook: DexOrJarPath = /data/app/pl.solidexplorer-1/base.apk, OutputPath = null.
08-26 02:20:07.423 30771-30771/io.virtualapp:p7 D/IOHook: DexOrJarPath = /data/app/pl.solidexplorer-1/base.apk, OutputPath = null.
08-26 02:20:07.433 30709-30709/io.virtualapp:p9 E/ActivityThread: Failed to find provider info for pl.solidexplorer.unlocker
08-26 02:20:07.447 30771-30771/io.virtualapp:p7 D/ACRA: ACRA is enabled for pl.solidexplorer, intializing...
08-26 02:20:07.456 30771-30771/io.virtualapp:p7 D/ACRA: Looking for error files in /data/user/0/io.virtualapp/virtual/data/user/0/pl.solidexplorer/files
08-26 02:20:07.456 30771-30771/io.virtualapp:p7 D/ACRA: Looking for error files in /data/user/0/io.virtualapp/virtual/data/user/0/pl.solidexplorer/files
08-26 02:20:07.672 30709-30812/io.virtualapp:p9 D/OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
08-26 02:20:07.685 30709-30709/io.virtualapp:p9 D/AndroidRuntime: Shutting down VM
08-26 02:20:07.686 30709-30709/io.virtualapp:p9 E/VClientImpl: java.lang.ClassCastException: android.os.BinderProxy cannot be cast to pl.solidexplorer.operations.x
                                                                   at pl.solidexplorer.operations.l.onServiceConnected(SourceFile:466)
                                                                   at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1223)
                                                                   at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1240)
                                                                   at android.os.Handler.handleCallback(Handler.java:739)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                   at android.os.Looper.loop(Looper.java:148)
                                                                   at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
08-26 02:20:07.686 30709-30709/io.virtualapp:p9 I/Process: Sending signal. PID: 30709 SIG: 9
08-26 02:20:07.787 28788-28799/io.virtualapp:x D/VActivityManagerService: Process com.ss.android.article.news died.
```
